export const PUBLIC_ARTIST_ROUTES = [
    { path: '/artistas', label: 'Roster de Artistas' },
    { path: '/artistas/eventos', label: 'Eventos' },
    { path: '/artistas/bodas', label: 'Bodas' },
    { path: '/artistas/ferias', label: 'Ferias & Fiestas' },
    { path: '/artistas/festivales', label: 'Festivales' },
    { path: '/artistas/ciudades', label: 'Ciudades' },
    { path: '/artistas/provincias', label: 'Provincias' },
    { path: '/artistas/municipios', label: 'Ayuntamientos' },
    { path: '/artistas/aniversarios', label: 'Aniversarios' },
    { path: '/artistas/cumpleaños', label: 'Cumpleaños' },
];
export const PRIVATE_ARTIST_ROUTES = [
    { path: '/artistas/dashboard', label: 'Dashboard Resumen', requiredRole: 'artist', icon: 'LayoutDashboard' },
    { path: '/artistas/profile', label: 'Perfil de Artista', requiredRole: 'artist', icon: 'User' },
    { path: '/artistas/media', label: 'Galería Media', requiredRole: 'artist', icon: 'Image' },
    { path: '/artistas/bio', label: 'Biografía Oficial', requiredRole: 'artist', icon: 'FileText' },
    { path: '/artistas/repertoire', label: 'Repertorio Musical', requiredRole: 'artist', icon: 'Music' },
    { path: '/artistas/bookings', label: 'Reserva & Directos', requiredRole: 'artist', icon: 'Calendar' },
    { path: '/artistas/contracts', label: 'Smart Contracts', requiredRole: 'artist', icon: 'FileCheck' },
    { path: '/artistas/pricing', label: 'Cachés & Paquetes', requiredRole: 'artist', icon: 'DollarSign' },
    { path: '/artistas/analytics', label: 'Streams & DSPs', requiredRole: 'artist', icon: 'TrendingUp' },
    { path: '/artistas/leads', label: 'Leads de Contratación', requiredRole: 'artist', icon: 'Mail' },
    { path: '/artistas/settings', label: 'Ajustes Cuenta', requiredRole: 'artist', icon: 'Settings' },
];
