/**
 * 🇪🇸 BASE DE DATOS ESTRUCTURADA DE MUNICIPIOS Y HUBS DE ESPAÑA (pSEO 2026)
 * Contiene los municipios estratégicos y hubs provinciales para cobertura en las 52 provincias.
 */

export interface SpanishMunicipality {
  slug: string;
  name: string;
  provinceSlug: string;
  isCoreHub?: boolean;
}

export const SPANISH_MUNICIPALITIES: SpanishMunicipality[] = [
  // 1. COMUNIDAD DE MADRID
  { slug: 'madrid', name: 'Madrid Capital', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'alcala-de-henares', name: 'Alcalá de Henares', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'alcobendas', name: 'Alcobendas', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'alcorcon', name: 'Alcorcón', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'aranjuez', name: 'Aranjuez', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'arganda-del-rey', name: 'Arganda del Rey', provinceSlug: 'madrid' },
  { slug: 'arroyomolinos', name: 'Arroyomolinos', provinceSlug: 'madrid' },
  { slug: 'boadilla-del-monte', name: 'Boadilla del Monte', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'ciempozuelos', name: 'Ciempozuelos', provinceSlug: 'madrid' },
  { slug: 'collado-villalba', name: 'Collado Villalba', provinceSlug: 'madrid' },
  { slug: 'colmenar-viejo', name: 'Colmenar Viejo', provinceSlug: 'madrid' },
  { slug: 'coslada', name: 'Coslada', provinceSlug: 'madrid' },
  { slug: 'fuenlabrada', name: 'Fuenlabrada', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'galapagar', name: 'Galapagar', provinceSlug: 'madrid' },
  { slug: 'getafe', name: 'Getafe', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'las-rozas', name: 'Las Rozas de Madrid', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'leganes', name: 'Leganés', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'majadahonda', name: 'Majadahonda', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'mostoles', name: 'Móstoles', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'navalcarnero', name: 'Navalcarnero', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'parla', name: 'Parla', provinceSlug: 'madrid' },
  { slug: 'pinto', name: 'Pinto', provinceSlug: 'madrid' },
  { slug: 'pozuelo-de-alarcon', name: 'Pozuelo de Alarcón', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'rivas-vaciamadrid', name: 'Rivas-Vaciamadrid', provinceSlug: 'madrid' },
  { slug: 'san-fernando-de-henares', name: 'San Fernando de Henares', provinceSlug: 'madrid' },
  { slug: 'san-lorenzo-de-el-escorial', name: 'San Lorenzo de El Escorial', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'san-sebastian-de-los-reyes', name: 'San Sebastián de los Reyes', provinceSlug: 'madrid' },
  { slug: 'torrejon-de-ardoz', name: 'Torrejón de Ardoz', provinceSlug: 'madrid', isCoreHub: true },
  { slug: 'torrelodones', name: 'Torrelodones', provinceSlug: 'madrid' },
  { slug: 'tres-cantos', name: 'Tres Cantos', provinceSlug: 'madrid' },
  { slug: 'valdemoro', name: 'Valdemoro', provinceSlug: 'madrid' },
  { slug: 'villaviciosa-de-odon', name: 'Villaviciosa de Odón', provinceSlug: 'madrid' },
  { slug: 'villanueva-de-la-canada', name: 'Villanueva de la Cañada', provinceSlug: 'madrid' },
  { slug: 'valdemorillo', name: 'Valdemorillo', provinceSlug: 'madrid' },

  // 2. TOLEDO & CASTILLA-LA MANCHA
  { slug: 'toledo', name: 'Toledo Capital', provinceSlug: 'toledo', isCoreHub: true },
  { slug: 'mentrida', name: 'Méntrida (Hub Central EAR)', provinceSlug: 'toledo', isCoreHub: true },
  { slug: 'talavera-de-la-reina', name: 'Talavera de la Reina', provinceSlug: 'toledo', isCoreHub: true },
  { slug: 'illescas', name: 'Illescas', provinceSlug: 'toledo', isCoreHub: true },
  { slug: 'torrijos', name: 'Torrijos', provinceSlug: 'toledo', isCoreHub: true },
  { slug: 'sesena', name: 'Seseña', provinceSlug: 'toledo' },
  { slug: 'fuensalida', name: 'Fuensalida', provinceSlug: 'toledo' },
  { slug: 'sonseca', name: 'Sonseca', provinceSlug: 'toledo' },
  { slug: 'quintanar-de-la-orden', name: 'Quintanar de la Orden', provinceSlug: 'toledo' },
  { slug: 'madridejos', name: 'Madridejos', provinceSlug: 'toledo' },
  { slug: 'consuegra', name: 'Consuegra', provinceSlug: 'toledo' },
  { slug: 'mora', name: 'Mora', provinceSlug: 'toledo' },
  { slug: 'bargas', name: 'Bargas', provinceSlug: 'toledo' },
  { slug: 'yuncos', name: 'Yuncos', provinceSlug: 'toledo' },
  { slug: 'ocana', name: 'Ocaña', provinceSlug: 'toledo' },
  { slug: 'escalona', name: 'Escalona', provinceSlug: 'toledo' },
  { slug: 'santa-cruz-de-retamar', name: 'Santa Cruz de Retamar', provinceSlug: 'toledo' },
  { slug: 'villacanas', name: 'Villacañas', provinceSlug: 'toledo' },
  { slug: 'la-puebla-de-montalban', name: 'La Puebla de Montalbán', provinceSlug: 'toledo' },
  { slug: 'navahermosa', name: 'Navahermosa', provinceSlug: 'toledo' },
  { slug: 'otero', name: 'Otero', provinceSlug: 'toledo' },

  // OTRAS PROVINCIAS CASTILLA-LA MANCHA
  { slug: 'ciudad-real', name: 'Ciudad Real', provinceSlug: 'ciudad-real', isCoreHub: true },
  { slug: 'puertollano', name: 'Puertollano', provinceSlug: 'ciudad-real' },
  { slug: 'tomelloso', name: 'Tomelloso', provinceSlug: 'ciudad-real' },
  { slug: 'alcazar-de-san-juan', name: 'Alcázar de San Juan', provinceSlug: 'ciudad-real' },
  { slug: 'valdepenas', name: 'Valdepeñas', provinceSlug: 'ciudad-real' },
  { slug: 'albacete', name: 'Albacete', provinceSlug: 'albacete', isCoreHub: true },
  { slug: 'hellin', name: 'Hellín', provinceSlug: 'albacete' },
  { slug: 'villarrobledo', name: 'Villarrobledo', provinceSlug: 'albacete' },
  { slug: 'almansa', name: 'Almansa', provinceSlug: 'albacete' },
  { slug: 'guadalajara', name: 'Guadalajara', provinceSlug: 'guadalajara', isCoreHub: true },
  { slug: 'azuqueca-de-henares', name: 'Azuqueca de Henares', provinceSlug: 'guadalajara' },
  { slug: 'cuenca', name: 'Cuenca', provinceSlug: 'cuenca', isCoreHub: true },
  { slug: 'tarancon', name: 'Tarancón', provinceSlug: 'cuenca' },

  // 3. CATALUÑA
  { slug: 'barcelona', name: 'Barcelona Capital', provinceSlug: 'barcelona', isCoreHub: true },
  { slug: 'hospitalet-de-llobregat', name: "L'Hospitalet de Llobregat", provinceSlug: 'barcelona', isCoreHub: true },
  { slug: 'badalona', name: 'Badalona', provinceSlug: 'barcelona', isCoreHub: true },
  { slug: 'terrassa', name: 'Terrassa', provinceSlug: 'barcelona', isCoreHub: true },
  { slug: 'sabadell', name: 'Sabadell', provinceSlug: 'barcelona', isCoreHub: true },
  { slug: 'mataro', name: 'Mataró', provinceSlug: 'barcelona' },
  { slug: 'santa-coloma-de-gramenet', name: 'Santa Coloma de Gramenet', provinceSlug: 'barcelona' },
  { slug: 'sant-cugat-del-valles', name: 'Sant Cugat del Vallès', provinceSlug: 'barcelona', isCoreHub: true },
  { slug: 'cornella-de-llobregat', name: 'Cornellà de Llobregat', provinceSlug: 'barcelona' },
  { slug: 'sant-boi-de-llobregat', name: 'Sant Boi de Llobregat', provinceSlug: 'barcelona' },
  { slug: 'manresa', name: 'Manresa', provinceSlug: 'barcelona' },
  { slug: 'rubi', name: 'Rubí', provinceSlug: 'barcelona' },
  { slug: 'vilanova-i-la-geltru', name: 'Vilanova i la Geltrú', provinceSlug: 'barcelona' },
  { slug: 'viladecans', name: 'Viladecans', provinceSlug: 'barcelona' },
  { slug: 'castelldefels', name: 'Castelldefels', provinceSlug: 'barcelona' },
  { slug: 'granollers', name: 'Granollers', provinceSlug: 'barcelona' },
  { slug: 'sitges', name: 'Sitges', provinceSlug: 'barcelona', isCoreHub: true },
  { slug: 'tarragona', name: 'Tarragona', provinceSlug: 'tarragona', isCoreHub: true },
  { slug: 'reus', name: 'Reus', provinceSlug: 'tarragona' },
  { slug: 'girona', name: 'Girona', provinceSlug: 'gerona', isCoreHub: true },
  { slug: 'blanes', name: 'Blanes', provinceSlug: 'gerona' },
  { slug: 'lloret-de-mar', name: 'Lloret de Mar', provinceSlug: 'gerona' },
  { slug: 'lleida', name: 'Lleida', provinceSlug: 'lerida', isCoreHub: true },

  // 4. COMUNIDAD VALENCIANA
  { slug: 'valencia', name: 'Valencia Capital', provinceSlug: 'valencia', isCoreHub: true },
  { slug: 'gandia', name: 'Gandía', provinceSlug: 'valencia', isCoreHub: true },
  { slug: 'torrent', name: 'Torrent', provinceSlug: 'valencia' },
  { slug: 'paterna', name: 'Paterna', provinceSlug: 'valencia' },
  { slug: 'sagunto', name: 'Sagunto', provinceSlug: 'valencia' },
  { slug: 'alzira', name: 'Alzira', provinceSlug: 'valencia' },
  { slug: 'mislata', name: 'Mislata', provinceSlug: 'valencia' },
  { slug: 'burjassot', name: 'Burjassot', provinceSlug: 'valencia' },
  { slug: 'ontinyent', name: 'Ontinyent', provinceSlug: 'valencia' },
  { slug: 'xativa', name: 'Xàtiva', provinceSlug: 'valencia' },
  { slug: 'cullera', name: 'Cullera', provinceSlug: 'valencia' },
  { slug: 'alicante', name: 'Alicante', provinceSlug: 'alicante', isCoreHub: true },
  { slug: 'elche', name: 'Elche', provinceSlug: 'alicante', isCoreHub: true },
  { slug: 'torrevieja', name: 'Torrevieja', provinceSlug: 'alicante', isCoreHub: true },
  { slug: 'orihuela', name: 'Orihuela', provinceSlug: 'alicante' },
  { slug: 'benidorm', name: 'Benidorm', provinceSlug: 'alicante', isCoreHub: true },
  { slug: 'alcoy', name: 'Alcoy', provinceSlug: 'alicante' },
  { slug: 'elda', name: 'Elda', provinceSlug: 'alicante' },
  { slug: 'denia', name: 'Dénia', provinceSlug: 'alicante' },
  { slug: 'javea', name: 'Jávea', provinceSlug: 'alicante' },
  { slug: 'altea', name: 'Altea', provinceSlug: 'alicante' },
  { slug: 'calpe', name: 'Calpe', provinceSlug: 'alicante' },
  { slug: 'castellon', name: 'Castellón de la Plana', provinceSlug: 'castellon', isCoreHub: true },
  { slug: 'vila-real', name: 'Vila-real', provinceSlug: 'castellon' },

  // 5. ANDALUCÍA
  { slug: 'sevilla', name: 'Sevilla Capital', provinceSlug: 'sevilla', isCoreHub: true },
  { slug: 'dos-hermanas', name: 'Dos Hermanas', provinceSlug: 'sevilla' },
  { slug: 'alcala-de-guadaira', name: 'Alcalá de Guadaíra', provinceSlug: 'sevilla' },
  { slug: 'utrera', name: 'Utrera', provinceSlug: 'sevilla' },
  { slug: 'mairena-del-aljarafe', name: 'Mairena del Aljarafe', provinceSlug: 'sevilla' },
  { slug: 'ecija', name: 'Écija', provinceSlug: 'sevilla' },
  { slug: 'carmona', name: 'Carmona', provinceSlug: 'sevilla' },
  { slug: 'malaga', name: 'Málaga Capital', provinceSlug: 'malaga', isCoreHub: true },
  { slug: 'marbella', name: 'Marbella', provinceSlug: 'malaga', isCoreHub: true },
  { slug: 'mijas', name: 'Mijas', provinceSlug: 'malaga' },
  { slug: 'fuengirola', name: 'Fuengirola', provinceSlug: 'malaga' },
  { slug: 'velez-malaga', name: 'Vélez-Málaga', provinceSlug: 'malaga' },
  { slug: 'estepona', name: 'Estepona', provinceSlug: 'malaga' },
  { slug: 'benalmadena', name: 'Benalmádena', provinceSlug: 'malaga' },
  { slug: 'torremolinos', name: 'Torremolinos', provinceSlug: 'malaga' },
  { slug: 'ronda', name: 'Ronda', provinceSlug: 'malaga', isCoreHub: true },
  { slug: 'antequera', name: 'Antequera', provinceSlug: 'malaga' },
  { slug: 'cadiz', name: 'Cádiz', provinceSlug: 'cadiz', isCoreHub: true },
  { slug: 'jerez-de-la-frontera', name: 'Jerez de la Frontera', provinceSlug: 'cadiz', isCoreHub: true },
  { slug: 'algeciras', name: 'Algeciras', provinceSlug: 'cadiz' },
  { slug: 'san-fernando', name: 'San Fernando', provinceSlug: 'cadiz' },
  { slug: 'el-puerto-de-santa-maria', name: 'El Puerto de Santa María', provinceSlug: 'cadiz' },
  { slug: 'chiclana-de-la-frontera', name: 'Chiclana de la Frontera', provinceSlug: 'cadiz' },
  { slug: 'sanlucar-de-barrameda', name: 'Sanlúcar de Barrameda', provinceSlug: 'cadiz' },
  { slug: 'cordoba', name: 'Córdoba Capital', provinceSlug: 'cordoba', isCoreHub: true },
  { slug: 'lucena', name: 'Lucena', provinceSlug: 'cordoba' },
  { slug: 'puente-genil', name: 'Puente Genil', provinceSlug: 'cordoba' },
  { slug: 'granada', name: 'Granada Capital', provinceSlug: 'granada', isCoreHub: true },
  { slug: 'motril', name: 'Motril', provinceSlug: 'granada' },
  { slug: 'almunecar', name: 'Almuñécar', provinceSlug: 'granada' },
  { slug: 'baza', name: 'Baza', provinceSlug: 'granada' },
  { slug: 'almeria', name: 'Almería', provinceSlug: 'almeria', isCoreHub: true },
  { slug: 'roquetas-de-mar', name: 'Roquetas de Mar', provinceSlug: 'almeria' },
  { slug: 'el-ejido', name: 'El Ejido', provinceSlug: 'almeria' },
  { slug: 'jaen', name: 'Jaén', provinceSlug: 'jaen', isCoreHub: true },
  { slug: 'linares', name: 'Linares', provinceSlug: 'jaen' },
  { slug: 'ubeda', name: 'Úbeda', provinceSlug: 'jaen' },
  { slug: 'baeza', name: 'Baeza', provinceSlug: 'jaen' },
  { slug: 'huelva', name: 'Huelva', provinceSlug: 'huelva', isCoreHub: true },
  { slug: 'lepe', name: 'Lepe', provinceSlug: 'huelva' },
  { slug: 'almonte', name: 'Almonte', provinceSlug: 'huelva' },

  // 6. ZARAGOZA & ARAGÓN
  { slug: 'zaragoza', name: 'Zaragoza Capital', provinceSlug: 'zaragoza', isCoreHub: true },
  { slug: 'calatayud', name: 'Calatayud', provinceSlug: 'zaragoza' },
  { slug: 'utebo', name: 'Utebo', provinceSlug: 'zaragoza' },
  { slug: 'ejea-de-los-caballeros', name: 'Ejea de los Caballeros', provinceSlug: 'zaragoza' },
  { slug: 'huesca', name: 'Huesca', provinceSlug: 'huesca', isCoreHub: true },
  { slug: 'monzon', name: 'Monzón', provinceSlug: 'huesca' },
  { slug: 'barbastro', name: 'Barbastro', provinceSlug: 'huesca' },
  { slug: 'teruel', name: 'Teruel', provinceSlug: 'teruel', isCoreHub: true },
  { slug: 'alcaniz', name: 'Alcañiz', provinceSlug: 'teruel' },

  // 7. PAÍS VASCO, NAVARRA, LA RIOJA, CANTABRIA & ASTURIAS
  { slug: 'bilbao', name: 'Bilbao', provinceSlug: 'bilbao', isCoreHub: true },
  { slug: 'barakaldo', name: 'Barakaldo', provinceSlug: 'bilbao' },
  { slug: 'getxo', name: 'Getxo', provinceSlug: 'bilbao' },
  { slug: 'portugalete', name: 'Portugalete', provinceSlug: 'bilbao' },
  { slug: 'santurtzi', name: 'Santurtzi', provinceSlug: 'bilbao' },
  { slug: 'vitoria', name: 'Vitoria-Gasteiz', provinceSlug: 'vitoria', isCoreHub: true },
  { slug: 'san-sebastian', name: 'San Sebastián - Donostia', provinceSlug: 'bilbao', isCoreHub: true },
  { slug: 'irun', name: 'Irun', provinceSlug: 'bilbao' },
  { slug: 'pamplona', name: 'Pamplona - Iruña', provinceSlug: 'pamplona', isCoreHub: true },
  { slug: 'tudela', name: 'Tudela', provinceSlug: 'pamplona' },
  { slug: 'logrono', name: 'Logroño', provinceSlug: 'logrono', isCoreHub: true },
  { slug: 'calahorra', name: 'Calahorra', provinceSlug: 'logrono' },
  { slug: 'santander', name: 'Santander', provinceSlug: 'santander', isCoreHub: true },
  { slug: 'torrelavega', name: 'Torrelavega', provinceSlug: 'santander' },
  { slug: 'castro-urdiales', name: 'Castro-Urdiales', provinceSlug: 'santander' },
  { slug: 'gijon', name: 'Gijón', provinceSlug: 'gijon', isCoreHub: true },
  { slug: 'oviedo', name: 'Oviedo', provinceSlug: 'oviedo', isCoreHub: true },
  { slug: 'aviles', name: 'Avilés', provinceSlug: 'oviedo' },

  // 8. GALICIA
  { slug: 'a-coruna', name: 'A Coruña', provinceSlug: 'coruna', isCoreHub: true },
  { slug: 'santiago-de-compostela', name: 'Santiago de Compostela', provinceSlug: 'coruna', isCoreHub: true },
  { slug: 'ferrol', name: 'Ferrol', provinceSlug: 'coruna' },
  { slug: 'vigo', name: 'Vigo', provinceSlug: 'vigo', isCoreHub: true },
  { slug: 'pontevedra', name: 'Pontevedra', provinceSlug: 'pontevedra', isCoreHub: true },
  { slug: 'vilagarcia-de-arousa', name: 'Vilagarcía de Arousa', provinceSlug: 'pontevedra' },
  { slug: 'ourense', name: 'Ourense', provinceSlug: 'orense', isCoreHub: true },
  { slug: 'lugo', name: 'Lugo', provinceSlug: 'lugo', isCoreHub: true },

  // 9. CASTILLA Y LEÓN
  { slug: 'valladolid', name: 'Valladolid', provinceSlug: 'valladolid', isCoreHub: true },
  { slug: 'medina-del-campo', name: 'Medina del Campo', provinceSlug: 'valladolid' },
  { slug: 'burgos', name: 'Burgos', provinceSlug: 'burgos', isCoreHub: true },
  { slug: 'miranda-de-ebro', name: 'Miranda de Ebro', provinceSlug: 'burgos' },
  { slug: 'aranda-de-duero', name: 'Aranda de Duero', provinceSlug: 'burgos' },
  { slug: 'salamanca', name: 'Salamanca', provinceSlug: 'salamanca', isCoreHub: true },
  { slug: 'bejar', name: 'Béjar', provinceSlug: 'salamanca' },
  { slug: 'leon', name: 'León', provinceSlug: 'leon', isCoreHub: true },
  { slug: 'ponferrada', name: 'Ponferrada', provinceSlug: 'leon' },
  { slug: 'palencia', name: 'Palencia', provinceSlug: 'palma', isCoreHub: true },
  { slug: 'zamora', name: 'Zamora', provinceSlug: 'zamora', isCoreHub: true },
  { slug: 'benavente', name: 'Benavente', provinceSlug: 'zamora' },
  { slug: 'segovia', name: 'Segovia', provinceSlug: 'segovia', isCoreHub: true },
  { slug: 'avila', name: 'Ávila', provinceSlug: 'avila', isCoreHub: true },
  { slug: 'soria', name: 'Soria', provinceSlug: 'soria', isCoreHub: true },

  // 10. EXTREMADURA & MURCIA
  { slug: 'badajoz', name: 'Badajoz', provinceSlug: 'badajoz', isCoreHub: true },
  { slug: 'merida', name: 'Mérida', provinceSlug: 'badajoz', isCoreHub: true },
  { slug: 'don-benito', name: 'Don Benito', provinceSlug: 'badajoz' },
  { slug: 'almendralejo', name: 'Almendralejo', provinceSlug: 'badajoz' },
  { slug: 'caceres', name: 'Cáceres', provinceSlug: 'caceres', isCoreHub: true },
  { slug: 'plasencia', name: 'Plasencia', provinceSlug: 'caceres' },
  { slug: 'murcia', name: 'Murcia Capital', provinceSlug: 'murcia', isCoreHub: true },
  { slug: 'cartagena', name: 'Cartagena', provinceSlug: 'cartagena', isCoreHub: true },
  { slug: 'lorca', name: 'Lorca', provinceSlug: 'murcia' },
  { slug: 'molina-de-segura', name: 'Molina de Segura', provinceSlug: 'murcia' },
  { slug: 'alcantarilla', name: 'Alcantarilla', provinceSlug: 'murcia' },

  // 11. ISLAS BALEARES, CANARIAS, CEUTA Y MELILLA
  { slug: 'palma-de-mallorca', name: 'Palma de Mallorca', provinceSlug: 'palma', isCoreHub: true },
  { slug: 'ibiza', name: 'Ibiza / Eivissa', provinceSlug: 'palma', isCoreHub: true },
  { slug: 'manacor', name: 'Manacor', provinceSlug: 'palma' },
  { slug: 'las-palmas-de-gran-canaria', name: 'Las Palmas de Gran Canaria', provinceSlug: 'las-palmas', isCoreHub: true },
  { slug: 'telde', name: 'Telde', provinceSlug: 'las-palmas' },
  { slug: 'santa-cruz-de-tenerife', name: 'Santa Cruz de Tenerife', provinceSlug: 'santa-cruz', isCoreHub: true },
  { slug: 'san-cristobal-de-la-laguna', name: 'San Cristóbal de La Laguna', provinceSlug: 'santa-cruz' },
  { slug: 'arona', name: 'Arona', provinceSlug: 'santa-cruz' },
  { slug: 'adeje', name: 'Adeje', provinceSlug: 'santa-cruz' },
  { slug: 'ceuta', name: 'Ceuta', provinceSlug: 'ceuta', isCoreHub: true },
  { slug: 'melilla', name: 'Melilla', provinceSlug: 'melilla', isCoreHub: true }
];
