// Master Library: Banana Prompts & Situaciones Reales para Video Factory S-Class
// Repositorio Definitivo de 36 Situaciones Cinematográficas (bananaprompts.xyz / FastH3 Minimax Cookbook)

export type SituationCategory = 
  | "gala-solista" 
  | "bodas-vip" 
  | "vimume-clinico" 
  | "b2b-licitaciones" 
  | "festejos-populares" 
  | "macro-sensorial" 
  | "backstage-pro";

export interface RealSituation {
  id: string;
  category: SituationCategory;
  title: string;
  narrativeSubtitle: string;
  storytellingCaption: string;
  durationSeconds: number;
  cameraGear: string;
  lensSetup: string;
  lightingSetup: string;
  
  // Banana Prompt Hiper-detallado para FastH3 (AMD RX 7900 XTX 24GB)
  bananaPrompt: string;
  bananaSoundscape: string;
  bananaMusic: string;
  negativePrompt: string;
  cameraMotion: string;
  
  // Estilo de Color DaVinci Recomendado
  colorLUT: "gold" | "cyber" | "ruby" | "vimume" | "noir";
  transition: "zoom" | "glitch" | "slide" | "fade" | "flash";
  recommendedSfx: string;
  previewColor: string;
  previewVideoUrl?: string;
}

export const REAL_SITUATIONS_CATALOG: RealSituation[] = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 1. GALA & SOLISTA EDWIN AGUDELO (CONCIERTO & VIRTUOSISMO) [7 SITUACIONES]
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: "gala-piano-hands-close",
    category: "gala-solista",
    title: "Primer Plano: Manos al Piano de Cola",
    narrativeSubtitle: "CONCIERTO EN DIRECTO · SALA DE GALA",
    storytellingCaption: "CUANDO CADA NOTA TRANSMITE PURA MAESTRÍA",
    durationSeconds: 4,
    cameraGear: "ARRI Alexa 65, 8K Cinema Sensor",
    lensSetup: "Cooke Anamorphic/i Full Frame Plus 40mm T2.3",
    lightingSetup: "Chiaroscuro dramatic lighting, warm 3200K tungsten stage spotlights, volumetric haze, dust motes in light beam",
    bananaPrompt: "Cinematic 35mm anamorphic footage, extreme close-up shot of a master virtuoso pianist's hands playing an expressive piano piece on a Steinway & Sons concert grand piano, gleaming polished black lacquer reflections, warm amber theatre spotlight cutting through soft atmospheric haze, shallow depth of field with creamy bokeh, Kodak Vision3 500T 5219 film grain, photorealistic skin textures, slow camera push-in, 60fps slow motion.",
    bananaSoundscape: "Warm acoustic concert hall room reverberation, subtle breath of the artist, deep wooden body resonance of the piano.",
    bananaMusic: "Solo acoustic classical grand piano piece with virtuoso low-end resonance and expressive dynamic swell.",
    negativePrompt: "blurry, CGI, plastic skin, distorted hands, cartoon, oversaturated, artificial lights, amateur footage, noise",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "24K_Gold.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "gala-stage-medium-performer",
    category: "gala-solista",
    title: "Edwin Agudelo en Escenario Bajo Focos",
    narrativeSubtitle: "SOLISTA EXCLUSIVO · ETIQUETA S-CLASS",
    storytellingCaption: "EL ARTE DE CREAR MOMENTOS IRREPETIBLES",
    durationSeconds: 4,
    cameraGear: "RED V-Raptor 8K VV",
    lensSetup: "Panavision Primo 70mm f/1.4",
    lightingSetup: "Dual rim lighting, soft golden key light, blue backlight on theatre curtains",
    bananaPrompt: "Medium cinematic shot of Edwin Agudelo in a tailored luxury black tuxedo performing passionately on stage, focused intense expression, theatrical velvet curtain background, blue and golden anamorphic lens flares, rich color science, 8k resolution, authentic live concert atmosphere, slow tracking pan across the piano edge.",
    bananaSoundscape: "Live theatre acoustic room tone, subtle crowd murmur holding their breath in total silence.",
    bananaMusic: "Dramatic acoustic piano arpeggios building emotional tension.",
    negativePrompt: "low resolution, deformed face, bad proportions, fake stage, watermark, cartoonish, oversaturated",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "gold",
    transition: "slide",
    recommendedSfx: "1982 Brass.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "gala-guitar-solo-fretboard",
    category: "gala-solista",
    title: "Solo de Guitarra Acústica & Diapasón",
    narrativeSubtitle: "VIRTUOSISMO DE CUERDA · CALIDEZ ORGÁNICA",
    storytellingCaption: "LA SENSIBILIDAD DE LA CUERDA ESPAÑOLA",
    durationSeconds: 4,
    cameraGear: "Sony FX9 Full Frame 6K",
    lensSetup: "Leica APO-Macro-Summarit-S 120mm f/2.5",
    lightingSetup: "Warm side-lit tungsten glow, golden reflections on French polished spruce top",
    bananaPrompt: "Cinematic macro shot of musician's agile fingers sliding across the rosewood fretboard of a handcrafted Spanish concert guitar, silver bass strings vibrating in micro-detail, golden woodgrain lacquer gleam, intimate warm atmosphere, shallow depth of field, slow fluid dolly tracking along the guitar neck.",
    bananaSoundscape: "Intimate finger squeak on nylon winding, rich woody acoustic reverberation.",
    bananaMusic: "Virtuoso acoustic Spanish classical guitar solo with warm harmonic clarity.",
    negativePrompt: "distorted fingers, fake wood, blurry details, cartoon, unnatural anatomy",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "70s Classic.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "gala-standing-ovation-climax",
    category: "gala-solista",
    title: "Clímax & Ovación de Pie del Auditorio",
    narrativeSubtitle: "OVACIÓN EN VIVO · PÚBLICO DE PIE",
    storytellingCaption: "EL PÚBLICO PUESTO EN PIE RECONOCE LA EXCELENCIA",
    durationSeconds: 3,
    cameraGear: "Sony FX9 Full Frame 6K",
    lensSetup: "Sony 50mm G-Master f/1.2",
    lightingSetup: "House lights turning on, warm applause glow, dynamic camera sweep",
    bananaPrompt: "Cinematic shot from behind the performer looking out at an auditorium of well-dressed attendees giving an enthusiastic standing ovation, clapping hands, smiling faces, warm theatre house lighting glowing, shallow focus with beautiful bokeh on clapping hands in foreground, authentic live euphoria, documentary realism.",
    bananaSoundscape: "Thunderous standing ovation, enthusiastic theatre crowd cheering and loud acoustic hand clapping.",
    bananaMusic: "Triumphant musical resolution chord with rich piano sustain.",
    negativePrompt: "empty seats, stock photo look, stiff mannequins, digital artifacts, blurry faces",
    cameraMotion: "Orbit 360 (Gala Grand Piano)",
    colorLUT: "gold",
    transition: "fade",
    recommendedSfx: "808_Class.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "gala-backstage-dressing-mirror",
    category: "gala-solista",
    title: "Camerino & Concentración Previa",
    narrativeSubtitle: "EL RITUAL DEL ARTISTA · MINUTOS PREVIOS",
    storytellingCaption: "CADA GRAN CONCIERTO NACE EN EL SILENCIO",
    durationSeconds: 3,
    cameraGear: "ARRI Alexa Mini LF",
    lensSetup: "Cooke Speed Panchro 50mm T2.3",
    lightingSetup: "Hollywood vanity mirror tungsten bulbs, soft warm shadows, cinematic smoke",
    bananaPrompt: "Intimate cinematic shot in a backstage artist dressing room, Edwin Agudelo adjusting his bowtie in a mirror framed with round warm incandescent bulbs, taking a deep focused breath before walking out, tuxedo texture in sharp detail, atmospheric 35mm film mood, quiet tension, slow camera zoom-in.",
    bananaSoundscape: "Muffled distant crowd murmur through backstage door, clock ticking softly, quiet intake of breath.",
    bananaMusic: "Subtle low sub-bass drone with gentle reflective piano note.",
    negativePrompt: "harsh LED lights, messy background, low detail, cartoonish, oversaturated",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "noir",
    transition: "fade",
    recommendedSfx: "15 Inch Per Second.nksf.ogg",
    previewColor: "#ffffff",
    previewVideoUrl: "",
  },
  {
    id: "gala-soundcheck-empty-hall",
    category: "gala-solista",
    title: "Prueba de Sonido en Auditorio Vacío",
    narrativeSubtitle: "CALIBRACIÓN ACÚSTICA · SALA SOBERANA",
    storytellingCaption: "PERFECCIÓN TÉCNICA ANTES DE ABRIR PUERTAS",
    durationSeconds: 4,
    cameraGear: "RED V-Raptor 8K",
    lensSetup: "Angenieux Optimo Ultra 12x Zoom",
    lightingSetup: "Work lights, single spotlight on center stage, vast empty theatre seats in shadow",
    bananaPrompt: "Wide cinematic establishing shot of a grand historic opera house with empty velvet red seats, lone pianist on stage under a single working spotlight testing the piano acoustics, sound engineer at mixing board in silhouette in the foreground, breathtaking cathedral-like architecture, pristine symmetry.",
    bananaSoundscape: "Cavernous natural reverberation of single piano notes echoing in 1500-seat empty auditorium.",
    bananaMusic: "Staccato piano intervals testing spatial delay and low-end clarity.",
    negativePrompt: "cluttered, ugly modern stadium, flat lighting, digital noise, cartoon",
    cameraMotion: "Drone Aerial (Finca VIP Event)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "2 Bar Sequence.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "gala-midnight-encore-intimate",
    category: "gala-solista",
    title: "Bis Íntimo a Medianoche a la Luz de Velas",
    narrativeSubtitle: "SESIÓN PRIVADA VIP · ATMÓSFERA EXCLUSIVA",
    storytellingCaption: "LA MÚSICA EN SU ESTADO MÁS PURO",
    durationSeconds: 4,
    cameraGear: "Sony FX3 Full Frame",
    lensSetup: "Voigtländer Nokton 50mm f/1.2",
    lightingSetup: "Pure candlelight flicker, deep dark shadows, warm amber highlights on piano keys",
    bananaPrompt: "Intimate late-night performance shot in a dimly lit VIP salon, golden candle flames gently flickering on the grand piano music rack, deep shadows, warm amber light glinting on pianist's fingers, private salon concert for exclusive patrons, luxurious moody atmosphere, analog film warmth.",
    bananaSoundscape: "Gentle flame flicker, soft floorboard creak, breathy close-mic acoustic piano.",
    bananaMusic: "Nocturne style slow lyrical acoustic piano ballad with deep resonance.",
    negativePrompt: "bright lights, noise, artificial glow, CGI, plastic look",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "ruby",
    transition: "fade",
    recommendedSfx: "3D Chords.nksf.ogg",
    previewColor: "#FF2B44",
    previewVideoUrl: "",
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 2. BODAS VIP & FINCAS EXCLUSIVAS (ROMANCE & ALTA GAMA) [7 SITUACIONES]
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: "boda-golden-hour-dance",
    category: "bodas-vip",
    title: "El Vals Nupcial al Atardecer (Golden Hour)",
    narrativeSubtitle: "FINCAS EXCLUSIVAS · MOMENTO CULMINANTE",
    storytellingCaption: "UN BAILE QUE RECORDARÁN TODA SU VIDA",
    durationSeconds: 4,
    cameraGear: "ARRI Alexa Mini LF",
    lensSetup: "Leica Summilux-C 35mm T1.4",
    lightingSetup: "Golden hour sunset backlit, lens flare, warm romantic amber glow, outdoor fairy lights",
    bananaPrompt: "Cinematic romantic 4K slow motion shot, golden hour sunset light, bride in an elegant silk wedding dress and groom in a dark tailored suit slow dancing on a historic stone terrace of a Spanish luxury cortijo, hanging warm fairy lights sparkling overhead, gentle breeze in bride's hair, authentic tears of happiness, cinematic warm graded colors.",
    bananaSoundscape: "Gentle evening breeze rustling olive trees, soft outdoor courtyard reverberation.",
    bananaMusic: "Tender romantic acoustic piano and violin ballad with sweet harmonic swells.",
    negativePrompt: "stiff poses, fake sunset, washed out colors, artificial CGI, unnatural smiles",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "ruby",
    transition: "fade",
    recommendedSfx: "80s Bell.nksf.ogg",
    previewColor: "#FF2B44",
    previewVideoUrl: "",
  },
  {
    id: "boda-toast-champagne-guests",
    category: "bodas-vip",
    title: "Cóctel de Gala & Brindis con Champán",
    narrativeSubtitle: "EXPERIENCIA GASTRONÓMICA & MÚSICA EN DIRECTO",
    storytellingCaption: "MÚSICA ACÚSTICA QUE ELEVA CADA CONVERSACIÓN",
    durationSeconds: 3,
    cameraGear: "RED Komodo 6K",
    lensSetup: "Canon Cinema Prime 50mm T1.3",
    lightingSetup: "Evening garden party, crystal glass sparkle, warm tungsten lanterns",
    bananaPrompt: "Cinematic macro shot of crystal champagne glasses clinking in a toast at a luxury outdoor wedding cocktail, warm garden party fairy lights bokeh in the background, elegant guests laughing in blurred background, live musician subtly visible performing in background, high dynamic range, crisp fluid droplets on glass.",
    bananaSoundscape: "Delicate crystal champagne glass clinking, elegant laughter and murmur of celebratory guests.",
    bananaMusic: "Sophisticated bossa nova / acoustic jazz piano background accompaniment.",
    negativePrompt: "plastic cups, dark underexposed, blurry mess, watermark, cheap party",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "80_Analog_Ding.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "boda-ceremony-aisle-walk",
    category: "bodas-vip",
    title: "Entrada Nupcial con Violín en Directo",
    narrativeSubtitle: "CEREMONIA SOLEMNE · EMOCIÓN PURA",
    storytellingCaption: "EL INSTANTE PRECISO EN QUE TODO CAMBIA",
    durationSeconds: 4,
    cameraGear: "ARRI Alexa Mini",
    lensSetup: "Zeiss Supreme Prime 50mm T1.5",
    lightingSetup: "Natural sunlight filtering through olive tree branches, soft dappled light",
    bananaPrompt: "Emotional slow-motion tracking shot of bride walking down floral petal aisle accompanied by live acoustic violin and grand piano, groom wiping away a genuine tear at the altar, guests smiling with misty eyes, romantic white floral arch, gentle breeze, hyper-realistic candid emotion.",
    bananaSoundscape: "Gentle footsteps on stone pathway, outdoor bird chirp, solemn silence of guests.",
    bananaMusic: "Emotive acoustic violin playing Pachelbel Canon in D with lush piano backing.",
    negativePrompt: "stiff actors, oversaturated flowers, bad lighting, amateur camera shake",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "gold",
    transition: "slide",
    recommendedSfx: "1975_Mini.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "boda-sunset-banquet-tables",
    category: "bodas-vip",
    title: "Banquete Imperial al Atardecer Bajo Candelabros",
    narrativeSubtitle: "ALTA GASTRONOMÍA · AMBIENTE DE ENSUEÑO",
    storytellingCaption: "DONDE CADA DETALLE ESTÁ AFINADO",
    durationSeconds: 4,
    cameraGear: "Sony FX6",
    lensSetup: "Sigma Cine 24mm T1.5",
    lightingSetup: "Twilight dusk blue sky contrasting with hundreds of tall tapered candles and crystal chandeliers",
    bananaPrompt: "Sweeping tracking shot down a majestic long imperial wedding banquet table set under ancient pergolas, tall candelabras with flickering flames, crystal wine glasses gleaming, lavish floral arrangements, guests laughing in evening attire, live acoustic quartet performing in background pavilion, magical blue hour atmosphere.",
    bananaSoundscape: "Warm communal dinner laughter, cutlery softly chiming on fine porcelain, distant live cello.",
    bananaMusic: "Upbeat acoustic Mediterranean waltz with rhythmic guitar and accordion.",
    negativePrompt: "empty tables, messy food, harsh flashes, washed out colors",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "ruby",
    transition: "fade",
    recommendedSfx: "80s_Analog.nksf.ogg",
    previewColor: "#FF2B44",
    previewVideoUrl: "",
  },
  {
    id: "boda-party-dancefloor-explosion",
    category: "bodas-vip",
    title: "Fiesta de Madrugada con Saxofonista en Directo",
    narrativeSubtitle: "BARRA LIBRE VIP · CLÍMAX DE CELEBRACIÓN",
    storytellingCaption: "LA ENERGÍA QUE HACE BAILAR A TODOS",
    durationSeconds: 3,
    cameraGear: "RED V-Raptor 8K",
    lensSetup: "Cooke Anamorphic 25mm T2.3",
    lightingSetup: "Dynamic beam lasers, golden confetti storm, warm stage wash",
    bananaPrompt: "High-energy cinematic slow-motion shot on a packed luxury wedding dancefloor, live saxophonist performing in the middle of dancing guests, gold and white confetti raining down in slow motion, bride jumping with joy, ecstatic party energy, warm anamorphic lens flares, 60fps cinematic fluidity.",
    bananaSoundscape: "Massive crowd cheer, confetti cannon boom, acoustic saxophone ringing clear.",
    bananaMusic: "Modern deep house track blended with virtuoso live acoustic saxophone hook.",
    negativePrompt: "empty floor, dark grainy mess, blurry faces, cheap disco lights",
    cameraMotion: "Orbit 360 (Gala Grand Piano)",
    colorLUT: "cyber",
    transition: "glitch",
    recommendedSfx: "808_Long_Kick.nksf.ogg",
    previewColor: "#00E5FF",
    previewVideoUrl: "",
  },
  {
    id: "boda-bridal-suite-morning",
    category: "bodas-vip",
    title: "Mañana de Preparativos & Melodía Matinal",
    narrativeSubtitle: "SUITE NUPCIAL · SERENIDAD PREVIA",
    storytellingCaption: "LA CALMA ANTES DEL GRAN MOMENTO",
    durationSeconds: 3,
    cameraGear: "ARRI Alexa Mini LF",
    lensSetup: "Canon Dream Lens 50mm f/0.95",
    lightingSetup: "High key sheer white curtain window daylight, dreamy soft contrast",
    bananaPrompt: "Dreamy cinematic shot in an antique Spanish palace bridal suite, bride in silk robe standing peacefully by an arched stone balcony looking out over mist-covered olive groves, acoustic guitar chords softly drifting up from courtyard below, delicate morning sun flare, ethereal elegance, Kodak Portra 160 tones.",
    bananaSoundscape: "Morning birdsong, gentle courtyard breeze, distant melodic acoustic guitar.",
    bananaMusic: "Soothing acoustic fingerstyle guitar with warm open tunings.",
    negativePrompt: "messy bedroom, cluttered makeup, harsh shadows, cartoonish",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "fade",
    recommendedSfx: "90s Pop Hook.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "boda-fireworks-finale-cortijo",
    category: "bodas-vip",
    title: "Fuegos Artificiales sobre la Finca",
    narrativeSubtitle: "BROCHE DE ORO · MEDIANOCHE MÁGICA",
    storytellingCaption: "EL FINAL PERFECTO PARA UNA FECHA IRREPETIBLE",
    durationSeconds: 4,
    cameraGear: "Sony FX9",
    lensSetup: "Leica Summilux 21mm f/1.4",
    lightingSetup: "Night sky illuminated by spectacular golden and emerald fireworks shells",
    bananaPrompt: "Cinematic wide angle shot from behind bride and groom embracing on a terrace, looking up as a dazzling display of golden fireworks bursts against the starry Spanish night sky above the historic cortijo estate, gold sparks illuminating their silhouettes, awe-struck expressions, cinematic epic scale.",
    bananaSoundscape: "Resonant fireworks explosions echoing across hills, crowd gasping in collective wonder.",
    bananaMusic: "Epic orchestral crescendo with soaring piano and triumphant percussion.",
    negativePrompt: "smoke-filled blur, CGI fireworks, low dynamic range, noisy darks",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "gold",
    transition: "flash",
    recommendedSfx: "8Bit_Artillary.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 3. VIMUME NEURO-MUSICOTERAPIA (IMPACTO SANITARIO & 40HZ) [6 SITUACIONES]
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: "vimume-senior-smile-awakening",
    category: "vimume-clinico",
    title: "Reconexión Cognitiva: Sonrisa y Mirada Lúcida",
    narrativeSubtitle: "PROTOCOLO CLÍNICO 40HZ · SALUD NEURONAL",
    storytellingCaption: "LA MÚSICA DESPIERTA RECUERDOS DONDE LAS PALABRAS NO LLEGAN",
    durationSeconds: 4,
    cameraGear: "Sony FX6 Cinema Line",
    lensSetup: "Zeiss Supreme Prime 50mm T1.5",
    lightingSetup: "Soft diffused morning window light, high key natural warmth, serene gentle mood",
    bananaPrompt: "Documentary cinematic 4K close-up shot, natural morning window illumination, an elderly Spanish woman with dementia sitting comfortably, her face softening into a genuine, peaceful smile of recognition as she listens to live acoustic music, realistic gentle wrinkles, sparkling clear eyes, tender compassionate atmosphere, Kodak Portra 400 natural skin tones.",
    bananaSoundscape: "Gentle natural room ambiance, soft breathing, peaceful domestic tranquility.",
    bananaMusic: "Serene 40Hz acoustic neuro-therapeutic piano melody with gentle binaural overtone warmth.",
    negativePrompt: "sad, hospital depressing look, harsh medical lights, CGI, cartoonish, low contrast",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "vimume",
    transition: "fade",
    recommendedSfx: "7 Worlds.nksf.ogg",
    previewColor: "#10b981",
    previewVideoUrl: "",
  },
  {
    id: "vimume-hands-therapist-connection",
    category: "vimume-clinico",
    title: "El Vínculo Humano: Manos y Calidez Terapeuta",
    narrativeSubtitle: "IMPACTO SROI 4.85X · LEY 49/2002",
    storytellingCaption: "CADA CONTRATACIÓN PRIVADA FINANCIA UNA SESIÓN CLÍNICA",
    durationSeconds: 3,
    cameraGear: "Blackmagic URSA Mini Pro 12K",
    lensSetup: "Cooke Panchro/i Classic 75mm T2.2",
    lightingSetup: "Warm side window sunbeam, gentle rim light on hands",
    bananaPrompt: "Close-up cinematic shot of a young music therapist gently holding the weathered hand of an elderly patient with warmth and tenderness, morning sunbeam falling across their clasped hands, acoustic guitar resting softly in the background out of focus, authentic empathy, documentary photorealism.",
    bananaSoundscape: "Warm acoustic guitar resonance fading into peaceful silence.",
    bananaMusic: "Warm acoustic nylon guitar harmonics with comforting melodic resolution.",
    negativePrompt: "ugly hands, deformed fingers, artificial plastic look, dark medical equipment",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "vimume",
    transition: "zoom",
    recommendedSfx: "70s Classic.nksf.ogg",
    previewColor: "#10b981",
    previewVideoUrl: "",
  },
  {
    id: "vimume-group-memory-circle",
    category: "vimume-clinico",
    title: "Círculo de Memoria Musical en Salón Senior",
    narrativeSubtitle: "TERAPIA GRUPAL NO INVASIVA · 40HZ GAMMA",
    storytellingCaption: "EL PODER COLECTIVO DE CANTAR CANCIONES DE LA INFANCIA",
    durationSeconds: 4,
    cameraGear: "Sony FX9",
    lensSetup: "Canon CN-E 35mm T1.5",
    lightingSetup: "Bright sunlit day center living room, potted plants, cheerful natural sunlight",
    bananaPrompt: "Cinematic documentary shot in a bright residential senior center lounge, small circle of elderly residents clapping their hands in sync with a live acoustic Spanish guitar player, genuine smiles on their faces, natural laughing expressions, heartwarming community atmosphere, authentic documentary realism.",
    bananaSoundscape: "Gentle rhythmic hand clapping, soft communal humming, warm nylon guitar strums.",
    bananaMusic: "Nostalgic Spanish popular folk melody played on acoustic guitar with 40Hz sub-frequencies.",
    negativePrompt: "depressing nursing home, grey clinical walls, fake actors, plastic expressions",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "vimume",
    transition: "slide",
    recommendedSfx: "2StepSeq.nksf.ogg",
    previewColor: "#10b981",
    previewVideoUrl: "",
  },
  {
    id: "vimume-cymatics-40hz-resonance",
    category: "vimume-clinico",
    title: "Visualización Cimática: Ondas Físicas a 40Hz",
    narrativeSubtitle: "CIENCIA NEUROACÚSTICA · BIO-FRECUENCIAS",
    storytellingCaption: "LA VIBRACIÓN EXACTA QUE ARMONIZA EL CEREBRO",
    durationSeconds: 3,
    cameraGear: "Phantom Flex 4K (High Speed 1000fps)",
    lensSetup: "Laowa 24mm f/14 2X Probe Lens",
    lightingSetup: "High-contrast clinical macro light, dark background, emerald and gold edge lighting",
    bananaPrompt: "Extreme macro high-speed 1000fps shot of fine golden sand grains on a black vibrating speaker plate dancing and organizing into sacred geometric Chladni mandala patterns driven by pure 40Hz sound vibration, fluid organic physics, hypnotic scientific beauty, emerald rim light.",
    bananaSoundscape: "Deep pure 40Hz low-frequency sinusoidal hum, organic rustle of vibrating sand grains.",
    bananaMusic: "Binaural 40Hz theta-gamma neuro-acoustic sound design with lush ambient chords.",
    negativePrompt: "CGI graphic, low fps, blurry sand, cartoon, fake physics",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "cyber",
    transition: "zoom",
    recommendedSfx: "12 OSC Bass.nksf.ogg",
    previewColor: "#00E5FF",
    previewVideoUrl: "",
  },
  {
    id: "vimume-doctor-clinical-observation",
    category: "vimume-clinico",
    title: "Validación Médica & Monitor de Constantes",
    narrativeSubtitle: "EVIDENCIA CLÍNICA · DESESCALADA DE FÁRMACOS",
    storytellingCaption: "DESESCALADA DEL 74% EN ANSIEDAD Y AGITACIÓN",
    durationSeconds: 3,
    cameraGear: "ARRI Alexa Mini",
    lensSetup: "Leica Summicron-C 50mm T2.0",
    lightingSetup: "Clean modern medical office daylight, crisp professional tones",
    bananaPrompt: "Cinematic commercial shot of a doctor in white coat reviewing a tablet showing EEG brainwave data stabilizing, smiling and nodding in satisfaction as acoustic music plays softly in the adjacent room, heart rate monitor showing a calm steady rhythm, scientific rigor combined with human empathy.",
    bananaSoundscape: "Subtle rhythmic medical monitor beep slowing to relaxed pace, soft distant acoustic guitar.",
    bananaMusic: "Minimalist acoustic piano with scientific clinical clarity and calm tempo.",
    negativePrompt: "dark hospital, chaotic emergency room, fake CGI charts, cartoonish",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "vimume",
    transition: "fade",
    recommendedSfx: "80_Analog_Ding.nksf.ogg",
    previewColor: "#10b981",
    previewVideoUrl: "",
  },
  {
    id: "vimume-family-emotional-embrace",
    category: "vimume-clinico",
    title: "Abrazo Intergeneracional Nieta y Abuelo",
    narrativeSubtitle: "EL IMPACTO REAL · CONEXIÓN FAMILIAR",
    storytellingCaption: "VOLVER A RECONOCER LA MIRADA DE QUIEN AMAS",
    durationSeconds: 4,
    cameraGear: "RED V-Raptor 8K",
    lensSetup: "Zeiss Otus 85mm f/1.4",
    lightingSetup: "Golden afternoon sunbeam, tender emotional softness, organic film flare",
    bananaPrompt: "Heartfelt slow-motion emotional shot, an adult granddaughter kneeling beside her elderly grandfather in a sunlit room, hugging him tightly as a single tear of joy rolls down her cheek, the grandfather smiling with eyes full of presence and love, live acoustic music in background, deep human emotion, raw documentary beauty.",
    bananaSoundscape: "Soft emotional sigh, gentle fabric rustle of embrace, warm room resonance.",
    bananaMusic: "Tender acoustic piano and cello duet with profound emotional weight.",
    negativePrompt: "fake crying, cheesy melodrama, artificial actors, washed out colors",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "fade",
    recommendedSfx: "24K_Gold.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 4. B2B, CORPORATIVO & LICITACIONES B2G [5 SITUACIONES]
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: "b2b-contract-signing-fountainpen",
    category: "b2b-licitaciones",
    title: "Firma de Contrato & Blindaje de Fecha (Stripe Price-Lock)",
    narrativeSubtitle: "GARANTÍA MUTUA · DEPÓSITO 100€ DEDUCIBLE",
    storytellingCaption: "SEGURIDAD JURÍDICA TOTAL SIN LETRA PEQUEÑA",
    durationSeconds: 3,
    cameraGear: "ARRI Alexa Mini",
    lensSetup: "Master Prime 35mm T1.3",
    lightingSetup: "Architectural executive desk lighting, clean modern shadows, high-end corporate tone",
    bananaPrompt: "Cinematic commercial macro shot, luxury wooden executive desk, hand signing a formal event performance contract with a brass fountain pen, dark ink flowing onto thick textured parchment paper, smartphone next to the contract showing a green verified Stripe Price-Lock payment notification, titanium watch on wrist, razor-sharp focus.",
    bananaSoundscape: "Subtle tactile sound of fountain pen nib on premium cotton paper, soft modern haptic phone chime.",
    bananaMusic: "Minimalist corporate tech piano pulse with elegant modern rhythm.",
    negativePrompt: "messy desk, cheap ballpoint pen, low quality, cartoon, digital distortion",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "808_Class.nksf.ogg",
    previewColor: "#00E5FF",
    previewVideoUrl: "",
  },
  {
    id: "b2b-boardroom-handshake-skyline",
    category: "b2b-licitaciones",
    title: "Apretón de Manos Institucional & Trato Cerrado",
    narrativeSubtitle: "ALIANZAS CORPORATIVAS · SPLIT SOBERANO 80/10/10",
    storytellingCaption: "ACUERDOS SÓLIDOS QUE BENEFICIAN A TODAS LAS PARTES",
    durationSeconds: 3,
    cameraGear: "Sony FX9",
    lensSetup: "Sony Cine 28mm T2.0",
    lightingSetup: "High-rise executive boardroom, floor-to-ceiling panoramic glass windows with city skyline sunset",
    bananaPrompt: "Medium wide shot of two corporate executives in sharp suits shaking hands firmly across a minimalist black glass conference table, massive city skyline visible through sunset panoramic windows behind them, mutual respect, professional confidence, sleek architectural modern design.",
    bananaSoundscape: "Quiet executive boardroom acoustics, gentle murmur of distant city traffic below.",
    bananaMusic: "Confident upbeat modern corporate tech synth pulse with acoustic piano stabs.",
    negativePrompt: "awkward handshake, blurry skyline, bad posture, cheap suits, AI hands",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "noir",
    transition: "slide",
    recommendedSfx: "4CTION.nksf.ogg",
    previewColor: "#ffffff",
    previewVideoUrl: "",
  },
  {
    id: "b2b-public-tender-envelope-seal",
    category: "b2b-licitaciones",
    title: "Apertura de Plica & Adjudicación B2G (<14.250€)",
    narrativeSubtitle: "CONTRATACIÓN PÚBLICA · ART. 118 LCSP",
    storytellingCaption: "CONTRATOS MENORES ADJUDICADOS CON RIGOR TÉCNICO",
    durationSeconds: 3,
    cameraGear: "ARRI Alexa Mini",
    lensSetup: "Cooke S4/i 40mm T2.0",
    lightingSetup: "Historic town hall council chamber, wood paneling, warm institutional chandeliers",
    bananaPrompt: "Cinematic medium close-up in an ornate municipal town hall chamber, official municipal council desk, an official envelope being opened with an antique letter opener revealing stamped tender adjudication documents, Spanish coat of arms in background, solemn administrative gravity, documentary photorealism.",
    bananaSoundscape: "Crisp paper envelope slicing open, heavy wood desk creak, official quiet council hall.",
    bananaMusic: "Solemn institutional cello and brass chords with steady clockwork tempo.",
    negativePrompt: "chaotic office, dirty desks, casual clothes, low resolution",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "gold",
    transition: "fade",
    recommendedSfx: "1982 Brass.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "b2b-stage-rigging-timelapse",
    category: "b2b-licitaciones",
    title: "Montaje Técnico & Rigging de Sonido",
    narrativeSubtitle: "PRODUCCIÓN BARE-METAL · INGENIERÍA EN VIVO",
    storytellingCaption: "INFRAESTRUCTURA DE SONIDO PROFESIONAL SIN FALLOS",
    durationSeconds: 4,
    cameraGear: "RED V-Raptor 8K",
    lensSetup: "Canon Cine 14mm T3.1 Ultra Wide",
    lightingSetup: "High-contrast festival outdoor stage rigging, heavy cranes, stage technicians in hard hats",
    bananaPrompt: "Dramatic wide angle shot of a massive concert festival stage being rigged by professional audio technicians, aluminum trussing being hoisted toward blue sky, line-array concert speaker clusters hanging in precision alignment, professional stage production bare-metal capability.",
    bananaSoundscape: "Motor hoist whine, heavy metal shackles clinking, radio walkie-talkie chatter.",
    bananaMusic: "Industrial electronic rhythm with driving bass pulse and precision percussion.",
    negativePrompt: "amateur backyard stage, chaotic scaffolding, cartoonish, low detail",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "cyber",
    transition: "glitch",
    recommendedSfx: "2Bar_Up_Mayhem.nksf.ogg",
    previewColor: "#00E5FF",
    previewVideoUrl: "",
  },
  {
    id: "b2b-telemetric-spl-sound-meter",
    category: "b2b-licitaciones",
    title: "Calibración Telemática & Límite Acústico (<85 dBA)",
    narrativeSubtitle: "LEY 37/2003 DEL RUIDO · PROTECCIÓN LEGAL",
    storytellingCaption: "PRESIÓN SONORA HOMOLOGADA SIN RIESGO DE SANCIONES",
    durationSeconds: 3,
    cameraGear: "Sony FX3",
    lensSetup: "Sony 90mm Macro f/2.8",
    lightingSetup: "Dark sound engineer control booth, glowing digital screens and audio limiters",
    bananaPrompt: "Macro cinematic shot of a calibrated Class 1 telemetric sound level meter display reading exactly 84.8 dBA in green digits, professional audio engineer hand adjusting precision rotary knob on master limiter rack, live concert visible in reflection of glass booth, strict acoustic compliance.",
    bananaSoundscape: "Clean tight controlled audio mix, zero distortion, precision acoustic mastering.",
    bananaMusic: "Modern electro-acoustic hybrid track with razor-sharp dynamic transients.",
    negativePrompt: "red peaking distortion, broken displays, amateur audio gear, blurry numbers",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "cyber",
    transition: "zoom",
    recommendedSfx: "808_Class.nksf.ogg",
    previewColor: "#00E5FF",
    previewVideoUrl: "",
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 5. FESTEJOS POPULARES & PLAZAS PÚBLICAS [4 SITUACIONES]
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: "festejo-plaza-night-celebration",
    category: "festejos-populares",
    title: "Verbena Nocturna en Plaza Mayor de Pueblo",
    narrativeSubtitle: "FESTEJOS POPULARES · EUFORIA COLECTIVA",
    storytellingCaption: "PUEBLOS ENTEROS VIBRANDO CON MÚSICA EN VIVO",
    durationSeconds: 4,
    cameraGear: "Sony FX9",
    lensSetup: "Zeiss 28mm f/2.0",
    lightingSetup: "Festive string bulb canopies across the plaza, illuminated Renaissance church facade, warm party wash",
    bananaPrompt: "Sweeping cinematic shot of a lively Spanish town square at night, hundreds of residents of all ages dancing and celebrating under a canopy of warm glowing street lights, illuminated stone clock tower in background, live music orchestra on outdoor stage, authentic festive joy, rich warm colors, 60fps.",
    bananaSoundscape: "Roar of festive crowd singing along, tambourines, brass fanfare, joyous celebration.",
    bananaMusic: "Lively acoustic brass and percussion Spanish pasodoble with festive energy.",
    negativePrompt: "empty streets, dark deserted plaza, violent crowd, blurry people",
    cameraMotion: "Drone Aerial (Finca VIP Event)",
    colorLUT: "gold",
    transition: "fade",
    recommendedSfx: "1982 Brass.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "festejo-street-brass-fanfare",
    category: "festejos-populares",
    title: "Pasacalles Festivo & Charanga por Callejas",
    narrativeSubtitle: "TRADICIÓN EN LA CALLE · SONIDO EN DIRECTO",
    storytellingCaption: "LA ALEGRÍA QUE RECORRE CADA RINCÓN DEL MUNICIPIO",
    durationSeconds: 3,
    cameraGear: "RED Komodo 6K",
    lensSetup: "Laowa 12mm Zero-D",
    lightingSetup: "Bright Spanish afternoon sun, white whitewashed village houses, vibrant fiesta banners",
    bananaPrompt: "Dynamic low-angle tracking shot moving backwards in front of a marching acoustic brass band and percussionists walking through narrow historic cobblestone streets, townspeople cheering from balconies throwing flower petals, contagious smiles, vibrant Spanish summer festival culture.",
    bananaSoundscape: "Loud resonant brass instruments in narrow stone alley, clapping hands, shouts of ole.",
    bananaMusic: "Energetic acoustic brass fanfare with thumping bass drum and snare rolls.",
    negativePrompt: "drab modern street, grey asphalt, blurry motion, cartoonish",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "gold",
    transition: "slide",
    recommendedSfx: "808_Tom.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "festejo-flamenco-duende-passion",
    category: "festejos-populares",
    title: "Cante Flamenco & Rasgueo de Guitarra con Duende",
    narrativeSubtitle: "RAÍZ & PASIÓN · ARTE ANDALUZ PURO",
    storytellingCaption: "LA FUERZA DEL DIRECTO QUE PONE LA PIEL DE GALLINA",
    durationSeconds: 4,
    cameraGear: "ARRI Alexa Mini",
    lensSetup: "Cooke 50mm T2.0",
    lightingSetup: "Rustic cellar tavern, single warm overhead light, deep red shadows, dust and sweat",
    bananaPrompt: "Intense cinematic close-up of a flamenco singer's expressive face singing with raw emotional passion, sweat glinting on temple, next to a Spanish guitarist delivering explosive rapid rasgueado chords on a cypress guitar, wooden cajón drum beat, intimate tablao atmosphere, unbridled Spanish duende.",
    bananaSoundscape: "Rhythmic hand claps (palmas), sharp heel stomp on wood stage, raspy emotional vocal cry.",
    bananaMusic: "Authentic bulería flamenco guitar with percussive cajón and syncopated palmas.",
    negativePrompt: "plastic tourist show, fake acting, flat lighting, amateur video",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "ruby",
    transition: "zoom",
    recommendedSfx: "3-Fngr Death Punch.nksf.ogg",
    previewColor: "#FF2B44",
    previewVideoUrl: "",
  },
  {
    id: "festejo-summer-communal-banquet",
    category: "festejos-populares",
    title: "Comida Popular de Hermandad Bajo Enramada",
    narrativeSubtitle: "CONVIVENCIA VECINAL · RAÍCES LOCALES",
    storytellingCaption: "MÚSICA QUE UNE A TODAS LAS GENERACIONES",
    durationSeconds: 3,
    cameraGear: "Sony FX6",
    lensSetup: "Sony 35mm f/1.4",
    lightingSetup: "Dappled afternoon sunlight filtering through pine branches, rustic trestle tables",
    bananaPrompt: "Warm documentary shot of an outdoor communal festival lunch in a village pine grove, giant paella pans, three generations of families toasting with local wine at long wooden tables, acoustic duo with accordion and guitar playing live between the tables, pure Mediterranean warmth.",
    bananaSoundscape: "Clinking wine carafes, laughter, acoustic accordion melodies weaving through pine trees.",
    bananaMusic: "Upbeat acoustic Mediterranean celebration waltz with acoustic guitars.",
    negativePrompt: "cold modern cafeteria, sterile look, blurry faces, cheap plastic",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "gold",
    transition: "fade",
    recommendedSfx: "80s Bell.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 6. MACRO & SENSORIAL AUDIÓFILO (LA CIENCIA DEL SONIDO) [4 SITUACIONES]
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: "macro-violin-bow-friction",
    category: "macro-sensorial",
    title: "Fricción de Cerdas en Cuerda de Violín (120fps)",
    narrativeSubtitle: "MACRO SENSORIAL · FÍSICA ACÚSTICA",
    storytellingCaption: "LA MICROSCOPÍA DEL SONIDO EN ESTADO PURO",
    durationSeconds: 4,
    cameraGear: "Phantom Flex 4K (Ultra Slow Motion)",
    lensSetup: "Infinity Photo-Optical TS-160 Macro Probe",
    lightingSetup: "High-intensity directional fiber-optic beam, pitch black background, gleaming golden bow hair",
    bananaPrompt: "Microscopic extreme slow-motion 120fps footage of horsehair violin bow sliding across a vibrating silver wound violin string, microscopic white rosin dust particles bursting into the air like tiny stars, extreme macro texture of twisted steel core, breathtaking cinematic physics of sound.",
    bananaSoundscape: "Harmonic high-frequency friction tone, microscopic crystalline resonance.",
    bananaMusic: "High harmonic violin overtone with deep sub-bass acoustic warmth.",
    negativePrompt: "digital CGI, 3D render look, low resolution, blurry macro",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "15 Inch Per Second.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "macro-piano-hammer-steel-impact",
    category: "macro-sensorial",
    title: "Macillos de Fieltro Golpeando Cuerdas de Acero",
    narrativeSubtitle: "MECÁNICA STEINWAY & SONS · 88 TECLAS",
    storytellingCaption: "EL GOLPE MECÁNICO QUE SE CONVIERTE EN EMOCIÓN",
    durationSeconds: 4,
    cameraGear: "Sony FX3 Macro Rig",
    lensSetup: "Venus Optics Laowa 24mm f/14 2X Macro",
    lightingSetup: "Internal gold cast-iron piano plate illuminated by soft micro-LED rim light",
    bananaPrompt: "Extreme interior macro shot inside a concert grand piano, wooden hammer with white felt head rising and striking thick copper wound bass strings in slow motion, heavy strings oscillating visibly, polished golden cast-iron soundboard harp reflections, mechanical elegance.",
    bananaSoundscape: "Heavy visceral wooden piano thud, massive deep bass piano string oscillation.",
    bananaMusic: "Deep low-end acoustic piano strike (A0 27.5 Hz) reverberating indefinitely.",
    negativePrompt: "fake plastic piano, CGI, blurry strings, cartoon",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "808_Long_Kick.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "macro-analog-console-faders",
    category: "macro-sensorial",
    title: "Faders de Mesa Analógica & Vúmetros Analógicos",
    narrativeSubtitle: "ESTUDIO DE MASTERIZACIÓN · PRECISIÓN ANALÓGICA",
    storytellingCaption: "CALIDEZ DE VÁLVULAS Y CONTROL MILIMÉTRICO",
    durationSeconds: 3,
    cameraGear: "ARRI Alexa Mini",
    lensSetup: "Cooke Panchro 75mm T2.2",
    lightingSetup: "Vintage SSL console desk lights, glowing needle VU meters in warm amber",
    bananaPrompt: "Cinematic macro shot of motorized faders gliding upward on a vintage 48-channel Neve analog recording console, dual backlit needle VU meters bouncing rhythmically in the warm analog zone, polished brushed aluminum and warm wooden side cheeks, studio craftsmanship.",
    bananaSoundscape: "Warm analog tape hiss, soft mechanical fader click, punchy dynamic master audio.",
    bananaMusic: "Rich analog warmth acoustic master track with wide stereo panorama.",
    negativePrompt: "cheap plastic mixer, modern digital computer screen, flat lighting",
    cameraMotion: "Tracking Pan (Slow Left to Right)",
    colorLUT: "gold",
    transition: "slide",
    recommendedSfx: "24K_Gold.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "macro-vinyl-needle-groove",
    category: "macro-sensorial",
    title: "Aguja Fonocaptora en el Surco de Vinilo",
    narrativeSubtitle: "ALTA FIDELIDAD AUDIÓFILA · ANALÓGICO PURO",
    storytellingCaption: "EL REGISTRO FÍSICO DE LA MÚSICA",
    durationSeconds: 3,
    cameraGear: "RED Komodo 6K",
    lensSetup: "Canon MP-E 65mm 1-5x Macro",
    lightingSetup: "High-contrast rim light on black spinning vinyl record, diamond needle sparkle",
    bananaPrompt: "Microscopic cinematic tracking shot of an elliptical diamond stylus dropping smoothly into the microgroove of a spinning black vinyl LP, microscopic dust motes floating, golden reflections on rotating vinyl rim, timeless analog soul, warm cinematic grain.",
    bananaSoundscape: "Classic satisfying vinyl needle drop thump, delicate dust crackle fading into warm music.",
    bananaMusic: "Warm vintage acoustic piano track with subtle vinyl surface warmth.",
    negativePrompt: "digital distortion, plastic turntable, low res, CGI",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "noir",
    transition: "fade",
    recommendedSfx: "80s_Analog.nksf.ogg",
    previewColor: "#ffffff",
    previewVideoUrl: "",
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 7. BACKSTAGE, CREACIÓN & ENSAYO PROFESIONAL [3 SITUACIONES]
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: "backstage-hands-metronome-warmup",
    category: "backstage-pro",
    title: "Calentamiento con Metrónomo Clásico de Madera",
    narrativeSubtitle: "DISCIPLINA & RIGOR · EL TEMPO EXACTO",
    storytellingCaption: "MILES DE HORAS DE ENSAYO PARA UN MINUTO PERFECTO",
    durationSeconds: 3,
    cameraGear: "Sony FX6",
    lensSetup: "Sony 50mm f/1.2 G-Master",
    lightingSetup: "Single vintage desk lamp warm circle of light, dark study room",
    bananaPrompt: "Intimate cinematic shot in a warm wood-paneled practice room, mechanical brass metronome pendulum swinging back and forth, pianist's hands practicing rapid chromatic scales on upright piano keys, intense concentration, sweat drop on brow, dedication to perfection.",
    bananaSoundscape: "Steady mechanical wooden metronome click (120 BPM), rapid crisp piano key attacks.",
    bananaMusic: "Precise classical piano etude practicing rapid finger agility.",
    negativePrompt: "digital smartphone app, modern plastic metronome, messy room",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "zoom",
    recommendedSfx: "5th Avenue.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "backstage-artist-sheet-music-notes",
    category: "backstage-pro",
    title: "Anotaciones a Lápiz Sobre la Partitura",
    narrativeSubtitle: "EL PROCESO CREATIVO · DETALLES DE INTERPRETACIÓN",
    storytellingCaption: "LA MÚSICA SE REINVENTA EN CADA LECTURA",
    durationSeconds: 3,
    cameraGear: "ARRI Alexa Mini",
    lensSetup: "Cooke Speed Panchro 40mm T2.3",
    lightingSetup: "Soft reading desk lamp, deep paper texture, graphite sheen",
    bananaPrompt: "Close-up shot of musician's hand with vintage graphite pencil writing expressive dynamic markings (pianissimo, rubato) on yellowed parchment musical sheet paper resting on piano music stand, graphite dust, focused artistic intensity, timeless craftsmanship.",
    bananaSoundscape: "Delicate scratch of graphite pencil on textured cotton sheet music paper, page turning.",
    bananaMusic: "Reflective solitary acoustic piano motif testing phrasing options.",
    negativePrompt: "computer screen, digital tablet, modern ballpoint pen, low detail",
    cameraMotion: "Static Master Shot (Concert Hall)",
    colorLUT: "gold",
    transition: "fade",
    recommendedSfx: "7 Worlds.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
  {
    id: "backstage-stage-curtain-entrance",
    category: "backstage-pro",
    title: "Vista Subjetiva (POV): Apertura de Telón y Entrada",
    narrativeSubtitle: "EL SALTO AL ESCENARIO · ADRENALINA PURA",
    storytellingCaption: "EL INSTANTE EN QUE COMIENZA LA MAGIA",
    durationSeconds: 4,
    cameraGear: "RED V-Raptor 8K (Gimbal Rig)",
    lensSetup: "Zeiss 21mm Ultra Wide T2.9",
    lightingSetup: "Extreme contrast: pitch black backstage transitioning into blinding stage floodlights",
    bananaPrompt: "First-person POV cinematic shot walking briskly from dark velvet backstage wings through the parting red curtains onto a brightly lit concert stage, sudden blast of golden spotlights and roaring crowd applause, seeing the grand piano waiting in center stage, exhilarating adrenaline rush.",
    bananaSoundscape: "Muffled heart thump accelerating, curtain fabric swish, sudden wall of roar and stadium cheers.",
    bananaMusic: "Tension riser building into massive triumphant orchestral piano impact.",
    negativePrompt: "flat lighting, empty room, shaky amateur phone video, cartoon",
    cameraMotion: "Dolly Push-in (Cinematic Slow)",
    colorLUT: "gold",
    transition: "flash",
    recommendedSfx: "24K_Gold.nksf.ogg",
    previewColor: "#ecb613",
    previewVideoUrl: "",
  },
];

// Arcos Narrativos Completos (Secuencias de 3 a 5 Situaciones Conectadas)
export const NARRATIVE_STORY_ARCS = [
  {
    id: "arc-gala-triunfal",
    name: "Arco 1: La Noche de Gala Triunfal (Edwin Agudelo)",
    description: "De la concentración en el camerino al clímax con ovación de pie del auditorio.",
    situationIds: [
      "gala-backstage-dressing-mirror",
      "gala-piano-hands-close",
      "gala-stage-medium-performer",
      "gala-standing-ovation-climax",
    ],
  },
  {
    id: "arc-boda-inolvidable",
    name: "Arco 2: Boda de Ensueño en Cortijo Exclusivo",
    description: "Preparativos matinales, entrada nupcial, vals al atardecer y fuegos artificiales.",
    situationIds: [
      "boda-bridal-suite-morning",
      "boda-ceremony-aisle-walk",
      "boda-golden-hour-dance",
      "boda-party-dancefloor-explosion",
      "boda-fireworks-finale-cortijo",
    ],
  },
  {
    id: "arc-vimume-impacto",
    name: "Arco 3: VIMUME — El Despertar a Través de la Música",
    description: "Reconexión cognitiva en personas mayores, validación médica y abrazo familiar.",
    situationIds: [
      "vimume-senior-smile-awakening",
      "vimume-cymatics-40hz-resonance",
      "vimume-hands-therapist-connection",
      "vimume-family-emotional-embrace",
    ],
  },
  {
    id: "arc-contrato-blindado",
    name: "Arco 4: Confianza Institucional & Reserva B2B / B2G",
    description: "La seguridad del precio cerrado, firma de contrato y la garantía soberana.",
    situationIds: [
      "b2b-contract-signing-fountainpen",
      "b2b-boardroom-handshake-skyline",
      "b2b-public-tender-envelope-seal",
      "b2b-telemetric-spl-sound-meter",
    ],
  },
  {
    id: "arc-festejos-populares",
    name: "Arco 5: Festejos Populares & Pasacalles de Pueblo",
    description: "Charanga callejera, cante flamenco con duende y la gran verbena en la plaza mayor.",
    situationIds: [
      "festejo-street-brass-fanfare",
      "festejo-flamenco-duende-passion",
      "festejo-summer-communal-banquet",
      "festejo-plaza-night-celebration",
    ],
  },
  {
    id: "arc-macro-sensorial",
    name: "Arco 6: La Ciencia del Sonido (Macro Sensorial)",
    description: "Fricción de arco de violín, macillos de piano, faders analógicos y surco de vinilo.",
    situationIds: [
      "macro-violin-bow-friction",
      "macro-piano-hammer-steel-impact",
      "macro-analog-console-faders",
      "macro-vinyl-needle-groove",
    ],
  },
  {
    id: "arc-backstage-virtuoso",
    name: "Arco 7: El Secreto del Virtuoso (Backstage & Ensayo)",
    description: "Metrónomo de madera, anotaciones en partitura y el salto definitivo al escenario.",
    situationIds: [
      "backstage-hands-metronome-warmup",
      "backstage-artist-sheet-music-notes",
      "backstage-stage-curtain-entrance",
      "gala-piano-hands-close",
    ],
  },
  {
    id: "arc-intimo-medianoche",
    name: "Arco 8: Concierto Privado VIP a la Luz de Velas",
    description: "Prueba de sonido en sala vacía, solo de guitarra acústica y bis íntimo a medianoche.",
    situationIds: [
      "gala-soundcheck-empty-hall",
      "gala-guitar-solo-fretboard",
      "gala-midnight-encore-intimate",
      "boda-toast-champagne-guests",
    ],
  },
];
